/* Curated evidence, not a demand-frequency dataset. Source snapshots: 2026-10-07.
 * zh is a paraphrase. quote is an attributed excerpt, accessible with its source.
 * Reddit scores and X likes have different meanings and must not be aggregated.
 */
window.LC_EVIDENCE = [
  {id:'R04',topic:'prep',platform:'r/travelchina',date:'2026-10-04',score:82,type:'post',core:true,
   quote:'I am trying to prepare (will get esim, alipay&wechat) - but I am (quite) a bit anxious.',
   zh:'eSIM、支付宝、微信都在准备，怎么还是有点慌？',en:'I’m preparing the right apps. Why do I still feel anxious?',
   context:['欧洲 · 首次来华','Europe · first visit'],
   need:['知道工具名称之后，仍需要确认准备是否充分。','Knowing which apps to install does not establish readiness.'],
   response:['行前检查：把准备事项、状态和下一步放在一起。','Preflight check: bring preparation, status and next steps together.'],
   boundary:['原帖直接表达行前焦虑，并未报告已经发生支付失败。票分属于整帖。','Direct preflight concern, not a report of a payment failure. The score belongs to the whole post.'],
   url:'https://www.reddit.com/r/travelchina/comments/1wxayfr/what_were_things_you_wish_you_knew_before_your/'},
  {id:'R06',topic:'payment',platform:'r/travelchina',date:'2025-08-22',score:31,type:'post',core:true,
   quote:'Passport verified, card added but still worried it won’t work',
   zh:'护照验证了，卡也绑了。落地真的能付款吗？',en:'Passport verified. Card added. Will payment actually work?',
   context:['美国 · 首次独自出行','US · first solo trip'],
   need:['已完成配置的用户，仍缺少对实际使用的信心。','Even a configured account can leave travelers unsure about their first payment.'],
   response:['支付准备与备用方式：呈现已完成步骤及替代路径。','Payment preparation and backups: show completed steps and alternatives.'],
   boundary:['作者说首次 solo，不能据此断言首次来华；担忧不等于银行卡已经失败。','The author says first solo trip, not necessarily first visit to China. Concern is not evidence of a card failure.'],
   url:'https://www.reddit.com/r/travelchina/comments/1mxjqrk/solo_china_trip_prep_worried_im_missing_something/'},
  {id:'R09',topic:'payment',platform:'r/travelchina',date:'2025-03-04',score:5,type:'post',core:true,
   quote:'is there any page where I can test or I can purchase anything, like I don’t mind sending 1usd 5usd or even 10usd, whatever as it will give me peace of mind',
   zh:'能不能出发前花一点钱，先试试支付能不能用？',en:'Can I make a small payment before leaving, just for peace of mind?',
   context:['为自己和家人做准备','Preparing for the family'],
   need:['用户明确询问支付自测，体现对就绪确认的需求。','An explicit request for a payment test reveals a need for reassurance.'],
   response:['设计 ¥1 验证流程和失败后的备用选择；当前通过模拟接口演示。','A ¥1 verification flow and fallback options, currently demonstrated with a mock API.'],
   boundary:['低票分但需求表达直接。不证明付费意愿、境外测试一定可行或一次验证适用于所有商户。评论中也有顺利完成旅行的反馈。','Low score, direct request. This does not prove willingness to pay, cross-border feasibility or universal payment acceptance. The thread also includes successful travel experiences.'],
   url:'https://www.reddit.com/r/travelchina/comments/1j2ztfs/is_there_a_way_to_test_wechat_alipay_online/'},
  {id:'C01',topic:'connectivity',platform:'r/travelchina',date:'2026-07-23',score:67,type:'comment',core:true,
   quote:'but an Airport where international visitors arrive?',
   zh:'国际机场的 Wi-Fi，为什么还是不知道怎么连？',en:'At an international airport, why is getting online still confusing?',
   context:['机场 Wi-Fi · 用户评论','Airport Wi-Fi · comment'],
   need:['游客需要找到适用于自己的认证和联网入口。','Travelers need a sign-in method that fits their situation.'],
   response:['按机场给出 Wi-Fi 指引、护照认证及人工服务入口。','Airport-specific Wi-Fi guidance, passport authentication and staff assistance.'],
   boundary:['这是对登录门槛的抱怨，不能理解为所有机场都要求中国手机号。上海机场官方提供护照认证。使用的是这条评论的分数。','This is frustration with access, not proof that every airport requires a Chinese phone number. Shanghai Airport documents passport authentication. The score belongs to this comment.'],
   url:'https://www.reddit.com/r/travelchina/comments/1v40u86/comment/oz7e7hi/',
   official:'https://www.shanghaiairport.com/enpd/fuwusheshi/index_lcid_418.html'},
  {id:'T01',topic:'transport',platform:'r/travelchina',date:null,score:null,type:'post',core:true,
   quote:'I will arrive at Beijing Airport PEK at 2:30AM in the morning. […] Availability of cars at that time of day?',
   zh:'凌晨 2:30 到北京，怎么去酒店？那时还有车吗？',en:'Landing at PEK at 2:30 AM. How do I get to my hotel?',
   context:['北京首都机场 · 深夜抵达','Beijing PEK · late arrival'],
   need:['交通选择需要结合到达时刻、目的地和可用方案。','Transport decisions depend on arrival time, destination and available options.'],
   response:['按落地时间、人数、行李和接机状态给出交通建议。','Transport rules based on arrival time, travelers, bags and booked transfers.'],
   boundary:['原帖正文已打开。未可靠取得原帖分数与绝对发表日期，因此不填。后续有顺利叫车反馈，不能据此宣称凌晨普遍无车。','The post body was opened. No reliable score or absolute publication date was available. Later feedback reports a successful pickup; this is not evidence that rides are generally unavailable at night.'],
   url:'https://www.reddit.com/r/travelchina/comments/1sd0hpe/didi_from_beijing_airport_pek_at_3am/'},
  {id:'N01',topic:'connectivity',platform:'r/travelchina',date:'2025-12-10',score:null,type:'post',core:true,supplement:true,
   quote:'Tried to purchase a eSIM through trip.com but my phone doesn’t support it […] any recommendations on what to do next?',
   zh:'在 Trip.com 买 eSIM 提示不兼容，我下一步该怎么办？',en:'Trip.com says my device is incompatible with the eSIM. What next?',
   context:['eSIM · 设备条件不同','eSIM · device constraints'],
   need:['购买同一工具可能遇到不同设备条件，指引需要有备用路线。','The same purchase flow meets different device conditions; guidance needs a fallback.'],
   response:['联网准备时提醒核对设备与运营商条件，并给出漫游或实体 SIM 等替代路径。','Check device and carrier conditions during preparation and provide roaming or physical-SIM alternatives.'],
   boundary:['补充检索，原帖与跟帖已打开。作者在跟帖自述手机被运营商锁定；不代表该型号普遍不支持 eSIM。未记录热度。','Supplemental research: post and replies opened. The author reports a carrier lock in a reply; this does not imply that the phone model generally lacks eSIM support. No score recorded.'],
   url:'https://www.reddit.com/r/travelchina/comments/1pipjf9/vpnesim/'},
  {id:'N02',topic:'payment',platform:'r/chinatravel',date:null,score:null,type:'post',supplement:true,
   quote:'I’m so confused… I thought this was a main app to download and get set up?? Did I mess something up?',
   zh:'卡提前绑好了，给朋友转钱却失败，是我设置错了吗？',en:'I linked my cards, but paying a friend failed. Did I set it up wrong?',
   context:['刚抵达上海 · 操作误解','Just arrived in Shanghai'],
   need:['需要区分具体操作与账户故障，避免把某项限制理解为整个支付不可用。','Travelers need to distinguish an operation-specific limit from an account-wide failure.'],
   response:['截图识别和知识条目解释适用范围，再提供可继续的操作。','Use screenshot classification and knowledge entries to explain scope and next actions.'],
   boundary:['原帖及作者后续回复已打开：作者说明向商户付款后来正常。不能把个人转账失败写成普遍无法付款。未可靠取得绝对日期和票分。','Post and follow-up opened: the author later reports successful merchant payments. A failed person-to-person transfer is not general payment failure. Absolute date and score not reliably obtained.'],
   url:'https://www.reddit.com/r/chinatravel/comments/1sn03lg/first_time_trying_to_use_alipay_in_china_it_did/'},
  {id:'X01',topic:'payment',platform:'X',date:'2026-09-23',score:2268,type:'likes',history:true,
   quote:'without having a mental breakdown',zh:'希望有一份不会让人崩溃的外卡绑定教程。',en:'A less overwhelming guide to linking a foreign card, please.',context:['历史记录 · 待在线复核','Historical · recheck needed'],
   need:['操作教程可能存在共鸣。','A signal of interest in clearer setup guidance.'],response:['行前图文教程。','Step-by-step preflight tutorials.'],boundary:['本轮原帖返回 403。2,268 为旧采集 likes，不能混同总互动，也不能确认作者是首访游客。不作为首页核心证据。','The original returned 403 in the documented review. 2,268 is historical likes, not total engagement. First-visit status is unknown. Excluded from core evidence.'],url:'https://x.com/fixer82601/status/2102740465695277467'},
  {id:'R01',topic:'prep',platform:'r/travelchina',date:'2025-11-19',score:594,type:'post',
   quote:'Mostly it worked for me.',zh:'支付多数时候正常，一种方式不行就换另一种。',en:'Payments mostly worked; a second method helped when one failed.',context:['首访游记 · 正反并存','First-visit report · mixed'],need:['具体失败时仍需备用路径。','Backups can help when a particular method fails.'],response:['备用支付和联网方式。','Alternative payment and connectivity routes.'],boundary:['整帖主要还谈疾病、天气和拥挤。594 不能归因于支付或第一小时问题，不使用夸张标题作为宣传。','The post also discusses illness, weather and crowds. Its score cannot be attributed to payments or the first hour. Its sensational title is not used as promotion.'],url:'https://www.reddit.com/r/travelchina/comments/1p1f8db/25_days_in_china_an_absolute_horror_trip_and_what/'},
  {id:'X02',topic:'prep',platform:'X',date:'2026-09-24',score:372,type:'likes',history:true,
   quote:'中国旅行のハードルは決済・ネット・地図',zh:'中国旅行的准备门槛：支付、网络、地图。',en:'The preparation hurdles: payments, internet and maps.',context:['历史记录 · 经验建议','Historical · travel advice'],need:['游客需要最小准备集合。','Travelers benefit from a minimal preparation set.'],response:['准备清单与任务导航。','Preparation checklist and task navigation.'],boundary:['旧采集记录，本轮原帖返回 403。作者首访身份未知，也认为掌握少量工具后旅行便利。','Historical record; original returned 403 in the documented review. First-visit status unknown. The author also says a few tools can make travel convenient.'],url:'https://x.com/kiriyasan_1123/status/2103260857589461418'},
  {id:'R02',topic:'prep',platform:'r/travelchina',date:'2025-05-15',score:257,type:'post',
   quote:'You essentially have to learn to use a whole new suite of apps',zh:'去过很多国家，也得重新学习一套本地应用。',en:'Even an experienced traveler has to learn a new suite of apps.',context:['经验丰富的旅行者','Experienced traveler'],need:['旅行能力不等于熟悉本地数字工具。','Travel experience does not imply familiarity with local digital services.'],response:['少量关键步骤与情境教程。','A small set of key steps and contextual tutorials.'],boundary:['作为背景材料，非首小时现场失败案例；作者同时认为掌握工具后旅行很便利。','Background context, not a first-hour failure. The author also describes travel as convenient after learning the tools.'],url:'https://www.reddit.com/r/travelchina/comments/1kmx6ob/trip_report_3_months_across_china/'},
  {id:'R03',topic:'payment',platform:'r/travelchina',date:'2024-11-03',score:84,type:'post',
   quote:'a message entirely in Mandarin',zh:'行前验证过了，后来又收到全中文的验证提示。',en:'Already verified, then a new verification message arrives entirely in Mandarin.',context:['历史背景 · 非首访','Historical · returning visitor'],need:['读懂状态和异常信息。','Understand status changes and unfamiliar error messages.'],response:['“我卡住了”截图 / 文字匹配。','“I’m stuck” screenshot and text matching.'],boundary:['用户不是首访者，旧版行为不能当作 2026 年普遍规则。原调研仅核对搜索索引正文，直接打开失败。','Not a first-time visitor. Historical behavior is not a universal 2026 rule. The original review checked indexed text; direct opening failed.'],url:'https://www.reddit.com/r/travelchina/comments/1gicqzq'},
  {id:'R05',topic:'prep',platform:'r/travelchina',date:'2025-06-19',score:53,type:'post',
   quote:'we know more or less what we wanna visit',zh:'游览路线大致定了，抵达时还需要做哪些准备？',en:'Our itinerary is mostly planned. What should we prepare for arrival?',context:['首次来华 · 主动规划','First visit · self-planned'],need:['会排行程的人仍需要本地工具准备指引。','People who can plan itineraries still need local preparation guidance.'],response:['行前清单与落地说明。','Preflight checklist and arrival guidance.'],boundary:['问题覆盖全旅程；整帖票分不能视为首小时需求支持率。原调研以索引正文核验。','The question covers the whole trip. The post score is not a first-hour demand rate. The original review used indexed text.'],url:'https://www.reddit.com/r/travelchina/comments/1lfa5yr/traveling_to_china_for_the_first_time_in_my_life/'},
  {id:'C02',topic:'prep',platform:'r/travelchina',date:'2026-10-04',score:46,type:'comment',
   quote:'don’t just set them up before leaving and assume everything will work.',zh:'不要装好应用，就默认落地后一切都能用。',en:'Don’t assume setup alone means everything will work on arrival.',context:['经验建议 · 同一讨论串','Travel advice · shared thread'],need:['区分已安装与已准备。','Distinguish installed from prepared.'],response:['清单状态、配置步骤和备用方式。','Checklist states, setup steps and backups.'],boundary:['与 R04、C03 来自同一讨论，不算独立样本。经验建议不证明统一境外测试可行。','Same discussion as R04 and C03, not an independent sample. Advice does not establish a universal overseas test.'],url:'https://www.reddit.com/r/travelchina/comments/1wxayfr/comment/pdrvdtf/'},
  {id:'R07',topic:'connectivity',platform:'r/travelchina',date:'2025-09-21',score:18,type:'post',
   quote:'Unfortunately, my phone doesn’t support eSIMs.',zh:'手机不支持 eSIM，北京机场能买实体 SIM 吗？',en:'My phone doesn’t support eSIM. Can I get a physical SIM at PEK?',context:['首访情侣 · 设备差异','First-visit couple · device limits'],need:['准备方案需要适配个体设备条件。','Preparation needs to account for individual device constraints.'],response:['设备条件提示及机场联网备用方法。','Device considerations and airport connectivity alternatives.'],boundary:['不是所有人都适用 eSIM 路线。本轮补充打开原帖；分数为文档中的索引记录。','An eSIM-only route does not fit every traveler. Original post additionally opened in this review; score comes from the research document snapshot.'],url:'https://www.reddit.com/r/travelchina/comments/1nmskx7'},
  {id:'C03',topic:'transport',platform:'r/travelchina',date:'2026-10-04',score:11,type:'comment',
   quote:'make sure it works before you get in a taxi',zh:'落地先买瓶水确认能付款，再坐出租车。',en:'Try a small purchase on arrival before getting in a taxi.',context:['首访后建议 · 同一讨论串','Post-trip advice · shared thread'],need:['支付确认与第一程交通相衔接。','Payment readiness and the first ride are connected tasks.'],response:['联网、支付和前往酒店的任务链。','A task sequence connecting data, payment and the hotel journey.'],boundary:['经验建议，不是所有交通方式都必须先测试数字支付。与 R04、C02 为同一讨论。','Travel advice, not a requirement to test digital payment before every transport option. Same discussion as R04 and C02.'],url:'https://www.reddit.com/r/travelchina/comments/1wxayfr/comment/pdrxrnt/'},
  {id:'R08',topic:'prep',platform:'r/chinatravel',date:'2026-03-12',score:8,type:'post',
   quote:'a bit overwhelmed by the digital prep',zh:'第一次去上海，数字准备已经有点让人应接不暇。',en:'First time in Shanghai, already overwhelmed by digital preparation.',context:['德国 · 首次来华','Germany · first visit'],need:['想知道最少需要准备哪些工具，以及它们各自的用途。','Understand the minimum set of tools and what each is for.'],response:['最小清单和按情境给出的操作帮助。','A minimal checklist and contextual help.'],boundary:['问题同时涉及签证和景点，这些不纳入落地助手范围。原调研以搜索索引正文核验。','The post also discusses visas and sightseeing, outside this product’s scope. The original review used indexed text.'],url:'https://www.reddit.com/r/chinatravel/comments/1rs2zsc/first_time_in_shanghai_for_3_nights_next_week/'}
];
